# Generated by Django 3.1.1 on 2020-09-01 19:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=10)),
                ('userame', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, validators=[main.models.validate_email])),
                ('isCandidate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='voted on')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='main.user')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='voter', to='main.user')),
            ],
        ),
    ]
