# Generated by Django 3.1.1 on 2020-09-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userame',
            new_name='username',
        ),
    ]
