# Generated by Django 3.1.1 on 2020-09-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200902_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
        migrations.AddField(
            model_name='user',
            name='hasVoted',
            field=models.BooleanField(default=False),
        ),
    ]
