# Generated by Django 3.1.1 on 2020-09-02 07:52

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200902_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(default='NOBATCH', max_length=10)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, validators=[main.models.validate_email])),
                ('isCandidate', models.BooleanField(default=False)),
                ('hasVoted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='main.userprofile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
