# Generated by Django 3.1.1 on 2020-09-02 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200902_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.RESTRICT, related_name='voter', to='main.userprofile'),
        ),
    ]
