# Generated by Django 3.1.1 on 2020-09-02 11:06

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200902_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='batch_year',
            field=models.IntegerField(validators=[main.models.validate_batch_year]),
        ),
    ]
