# Generated by Django 3.1.1 on 2020-09-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200903_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='NA', max_length=2),
        ),
    ]
