# Generated by Django 3.1.1 on 2020-09-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='batch',
            field=models.CharField(default='NOBATCH', max_length=20),
        ),
    ]
