# Generated by Django 3.1.1 on 2020-09-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_userprofile_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='isAdmin',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('DV', 'Developers'), ('IM', 'iMtech SAC'), ('MT', 'Mtech SAC'), ('NA', 'Not Applicable')], default='NA', max_length=2),
        ),
    ]
