# Generated by Django 3.1.1 on 2020-09-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200903_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hasVoted',
        ),
    ]
