# Generated by Django 3.1.1 on 2020-09-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200903_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
