# Generated by Django 3.1.1 on 2020-09-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_userprofile_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='salt',
            field=models.CharField(default='17f51fad65f7ea5c', max_length=30),
        ),
        migrations.AddField(
            model_name='vote',
            name='voteHash',
            field=models.CharField(default='nohash', max_length=65),
        ),
    ]
