# Generated by Django 3.1.1 on 2020-09-08 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200908_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='manifesto_images')),
                ('category', models.CharField(default='NOBATCH', max_length=30)),
                ('agenda', models.TextField(max_length=500)),
                ('link_1', models.CharField(blank=True, max_length=50)),
                ('link_2', models.CharField(blank=True, max_length=50)),
                ('link_3', models.CharField(blank=True, max_length=50)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
        ),
    ]
