# Generated by Django 3.1.1 on 2020-09-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_manifesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifesto',
            name='agenda',
        ),
        migrations.AddField(
            model_name='manifesto',
            name='agenda_1',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='agenda_2',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='agenda_3',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='contact_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='display_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='display_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='display_3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='intro',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='link_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='link_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='link_3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
