# Generated by Django 3.1.1 on 2020-09-09 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 22, 26, 21, 552126), verbose_name='voted on'),
        ),
        migrations.AlterField(
            model_name='election',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 22, 26, 21, 552098), verbose_name='voted on'),
        ),
    ]
