# Generated by Django 3.1.1 on 2020-09-09 19:22

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200909_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='endTime',
            field=models.DateTimeField(default=main.models.EndTime, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='election',
            name='startTime',
            field=models.DateTimeField(default=main.models.StartTime, verbose_name='start time'),
        ),
    ]
