# Generated by Django 3.1.1 on 2020-09-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200910_0052'),
        ('main', '0021_auto_20200910_0154'),
    ]

    operations = [
    ]
